name: Build NeoN on Windows

on:
  push:
    branches: [dev, main]

  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

  schedule:
    - cron: '00 8 * * 0'  # Runs at 10 AM CEST (08:00 UTC) every Sunday

  workflow_dispatch:      # Optional: allows manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  windows_msvc:
    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"
    name: msvc
    runs-on: [windows-latest]
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: configure
      run: |
        cmake --preset develop  -DKokkos_DIR="D:/dev/Kokkos/lib/cmake/Kokkos" -DNeoN_DEVEL_TOOLS=OFF -DNeoN_WITH_GINKGO=OFF -DNeoN_ENABLE_MPI_SUPPORT=OFF
      shell: cmd

    - name: build
      run: |
        cmake --build --preset develop
      shell: cmd

    - name: test
      run: |
        cmake --build --preset develop --target test
      shell: cmd
