name: NeoN + NeoFOAM LRZ GitLab CI

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, synchronize, reopened, unlabeled, labeled]
  schedule:
    - cron: '00 8 * * 0'  # Runs at 10 AM CEST (08:00 UTC) every Sunday
  workflow_dispatch:      # Allows manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-neon:
    name: Trigger NeoN + NeoFOAM CI on GPU
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    outputs:
      branch: ${{ steps.branch.outputs.branch }}

    if: "!contains(toJson(github.event.pull_request.labels.*.name), 'Skip-build')"

    env:
      LRZ_GROUP: greole
      LRZ_HOST: gitlab-ce.lrz.de
      REPO_NAME: ${{ github.event.repository.name }}
      NEOFOAM_REPO: NeoFOAM
      NEON_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
      NEON_TRIGGER_TOKEN: ${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}
      ADAPTER_PROJECT_TOKEN: ${{ secrets.NEOFOAM_LRZ_GITLAB_PROJECT_TOKEN }}
      ADAPTER_TRIGGER_TOKEN: ${{ secrets.NEOFOAM_LRZ_GITLAB_TRIGGER_TOKEN }}
      MAX_WAIT_MINUTES: 1440  # 24 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine branch
        id: branch
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request"* ]]; then
            BRANCH="$GITHUB_HEAD_REF"
          else
            BRANCH=${GITHUB_REF_NAME#refs/heads/}
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Push commit to NeoN LRZ GitLab
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add lrz https://oauth2:${NEON_PROJECT_TOKEN}@${{ env.LRZ_HOST }}/${{ env.LRZ_GROUP }}/${{ env.REPO_NAME }}.git
          git fetch origin ${{ steps.branch.outputs.branch }}
          git checkout -B ${{ steps.branch.outputs.branch }} origin/${{ steps.branch.outputs.branch }}
          git reset --hard origin/${{ steps.branch.outputs.branch }}
          git push --force lrz HEAD:refs/heads/${{ steps.branch.outputs.branch }}

      - name: Cancel running/pending NeoN LRZ CI pipelines
        if: ${{ github.event_name != 'push' }}
        run: |
          ./ci/github/cancel_triggered_pipelines.sh \
            "${{ env.REPO_NAME }}" \
            "${{ steps.branch.outputs.branch }}" \
            "${NEON_PROJECT_TOKEN}"

      - name: Trigger NeoN LRZ GitLab CI pipeline
        id: trigger-neon
        run: |
          ./ci/github/trigger_pipeline.sh \
            "${{ env.REPO_NAME }}" \
            "${{ steps.branch.outputs.branch }}" \
            "${NEON_PROJECT_TOKEN}" \
            "${NEON_TRIGGER_TOKEN}" \
            "variables[BENCHMARK]=false"

      # - name: Wait for NeoN LRZ GitLab CI pipeline
      #   run: |
      #     ./ci/github/wait_pipeline.sh \
      #       "${{ env.REPO_NAME }}" \
      #       "${{ steps.trigger-neon.outputs.pipeline_id }}" \
      #       "${NEON_PROJECT_TOKEN}"

      - name: Cancel running/pending NeoFOAM LRZ CI pipelines
        run: |
          ./ci/github/cancel_triggered_pipelines.sh \
            "${{ env.NEOFOAM_REPO }}" \
            "${{ steps.branch.outputs.branch }}" \
            "${ADAPTER_PROJECT_TOKEN}"

      - name: Trigger NeoFOAM LRZ GitLab CI pipeline
        id: trigger-adapter
        run: |
          ./ci/github/trigger_pipeline.sh \
            "${{ env.NEOFOAM_REPO }}" \
            "${{ steps.branch.outputs.branch }}" \
            "${ADAPTER_PROJECT_TOKEN}" \
            "${ADAPTER_TRIGGER_TOKEN}" \
            "variables[NEON_BRANCH]=${{ steps.branch.outputs.branch }}" \
            "variables[TRIGGER_SOURCE]=${{ github.event.repository.name }}" \
            "variables[BENCHMARK]=false"

      - name: Wait for NeoFOAM LRZ GitLab CI pipeline
        run: |
          ./ci/github/wait_pipeline.sh \
            "${{ env.NEOFOAM_REPO }}" \
            "${{ steps.trigger-adapter.outputs.pipeline_id }}" \
            "${ADAPTER_PROJECT_TOKEN}"

  benchmark:
    name: Benchmark NeoN on GPU
    runs-on: ubuntu-latest
    timeout-minutes: 1440 # 24 hours

    needs: [build-and-test-neon]
    if: contains(toJson(github.event.pull_request.labels), 'benchmark')

    env:
      LRZ_GROUP: greole
      LRZ_HOST: gitlab-ce.lrz.de
      REPO_NAME: ${{ github.event.repository.name }}
      BRANCH: ${{ needs.build-and-test-neon.outputs.branch }}
      NEON_PROJECT_TOKEN: ${{ secrets.GITLAB_PROJECT_TOKEN }}
      NEON_TRIGGER_TOKEN: ${{ secrets.LRZ_GITLAB_TRIGGER_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cancel running/pending NeoN LRZ CI pipelines
        run: |
          ./ci/github/cancel_triggered_pipelines.sh \
            "${{ env.REPO_NAME }}" \
            "${BRANCH}" \
            "${NEON_PROJECT_TOKEN}"

      - name: Trigger NeoN LRZ GitLab CI pipeline for benchmarking
        id: trigger-neon
        run: |
          ./ci/github/trigger_pipeline.sh \
            "${{ env.REPO_NAME }}" \
            "${BRANCH}" \
            "${NEON_PROJECT_TOKEN}" \
            "${NEON_TRIGGER_TOKEN}" \
            "variables[BENCHMARK]=true"

      - name: Wait for NeoN LRZ GitLab CI pipeline for benchmarking
        run: |
          ./ci/github/wait_pipeline.sh \
            "${{ env.REPO_NAME }}" \
            "${{ steps.trigger-neon.outputs.pipeline_id }}" \
            "${NEON_PROJECT_TOKEN}"
